version: "3"

services:
#Global containers
  nginx_proxy:
    image: jwilder/nginx-proxy
    ports:
       - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretkey
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=password

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql_db:/var/lib/postgresql/data

  redis:
    image: redis:6.0-rc-alpine

#USERS FRONT
  users_front:
    depends_on:
      - rabbitmq
      - redis
      - websocket
    build: ./UsersFront
    restart: always
    environment:
      - VIRTUAL_HOST=users.simple.com
      - VIRTUAL_PORT=8080
    volumes:
      - ./UsersFront:/usr/src/app

  front_end:
    build: ./FrontEnd
    environment:
      - VIRTUAL_HOST=front.simple.com
      - VIRTUAL_PORT=8080
    volumes:
      - ./FrontEnd:/usr/src/app

# USERS LISTENER
  users_back:
    depends_on:
      - rabbitmq
      - redis
      - websocket
    build: ./Users
    restart: always
    volumes:
      - ./Users:/usr/src/app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq_user
      - RABBITMQ_PASS=password

  websocket:
    build: ./WebSocket
    restart: always
    volumes:
      - ./dist:/usr/src/app/dist
    environment:
      - VIRTUAL_HOST=ws.simple.com
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=rabbitmq_user
      - RMQ_PASS=password
    volumes:
      - ./WebSocket:/usr/src/app

volumes:
  psql_db:
