version: "3"

services:
#Global containers
  nginx_proxy:
    image: jwilder/nginx-proxy
    ports:
       - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  rabbitmq:
    image: rabbitmq:3-alpine
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=secretkey
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=password

  rabbit_mq_management:
    image: rabbitmq:3-management
    environment:
      - VIRTUAL_HOST=rabbitmq.manage.com
      - VIRTUAL_PORT=15672
      - RABBITMQ_DEFAULT_USER="username"
      - RABBITMQ_DEFAULT_PASS="password"

  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - psql_db:/var/lib/postgresql/data

  redis:
    image: redis:6.0-rc-alpine

#USERS FRONT
  users_front:
    depends_on:
      - rabbitmq
    image: nginx:1.17-alpine
    restart: always
    environment:
      - VIRTUAL_HOST=simple.users.com
    volumes:
      - ./UsersFront:/usr/src/app
      - ./UsersFront/nginx.conf:/etc/nginx/conf.d/site.conf
    links:
      - users_front_php

  users_front_php:
    image: php:7.4-fpm
    volumes:
      - ./UsersFront:/usr/src/app

# USERS LISTENER
  users_back:
    depends_on:
      - rabbitmq
    build: ./Users
    restart: always

networks:
  default:
    external:
      name: simple_microservice

volumes:
  psql_db: